language: go
go:
  - '1.6'
  - '1.7'
before_install:
  - mkdir -p $GOPATH/bin
install:
  - make deps
script:
  - make test
deploy:
  - provider: script
    script: make release-all
    on:
      tags: true
      go: '1.7'
