language: go
go:
  - '1.5'
  - '1.6'
before_install:
  - mkdir -p $GOPATH/bin
env:
  - GO15VENDOREXPERIMENT=1
install:
  - make deps
script:
  - make test
deploy:
  - provider: script
    script: make release-all
    on:
      tags: true
      go: '1.6'
